/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package clinicmanagement.ui;

import clinicmanagement.dao.DepartmentDAO;
import clinicmanagement.entities.Department;
import java.math.BigDecimal;
import javax.swing.JOptionPane;

/**
 *
 * @author nguye
 */
public class AddDepartmentDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddDepartmentDialog.class.getName());
     private Department departmentToUpdate;
    /**
     * Creates new form CreateUserByAdminDialog
     */
    /**
     * Creates new form AddDepartmentDialog
     */
    public AddDepartmentDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.departmentToUpdate = null;
        btnSave.setText("Add department");
    }
      public AddDepartmentDialog(java.awt.Frame parent, boolean modal, Department departmentToUpdate) {
        super(parent, modal);
        initComponents();
        this.departmentToUpdate = departmentToUpdate;
        btnSave.setText("Update");
        populateFields(); 
    }
      private void populateFields() {
        if (departmentToUpdate != null) {
            txtDepartmentName.setText(departmentToUpdate.getDepartmentName());
            txtDescription.setText(departmentToUpdate.getDescription());
            txtConsultationFee.setText(departmentToUpdate.getConsultationFee().toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelDepartmentName = new javax.swing.JLabel();
        LabelDescription = new javax.swing.JLabel();
        LabelconcultationFee = new javax.swing.JLabel();
        txtDepartmentName = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        txtConsultationFee = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LabelDepartmentName.setText("DepartmentName: ");

        LabelDescription.setText("Description:");

        LabelconcultationFee.setText("consultationFee:");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelDepartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelconcultationFee, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDepartmentName)
                            .addComponent(txtDescription)
                            .addComponent(txtConsultationFee, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(btnSave)
                        .addGap(59, 59, 59)
                        .addComponent(btnCancel)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelDepartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDepartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(LabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelconcultationFee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConsultationFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String departmentName = txtDepartmentName.getText().trim();
        String description = txtDescription.getText().trim();
        String consultationFee = txtConsultationFee.getText().trim();
        if(departmentName.isEmpty() || description.isEmpty() || consultationFee.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ các trường.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        BigDecimal fee = new BigDecimal(consultationFee);
        try 
        {
            DepartmentDAO dao = new DepartmentDAO();
            boolean success = false;
            if(departmentToUpdate == null)
            {
                Department newDepartment = new Department();
                newDepartment.setDepartmentName(departmentName);
                newDepartment.setDescription(description);
                newDepartment.setConsultationFee(fee);
                if (success) {
                    JOptionPane.showMessageDialog(this, "Thêm khoa mới thành công!");
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm khoa mới thất bại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
            else {  
                departmentToUpdate.setDepartmentName(departmentName);
                departmentToUpdate.setDescription(description);
                departmentToUpdate.setConsultationFee(fee);
                success = dao.updateDepartment(departmentToUpdate);
                if (success) {
                    JOptionPane.showMessageDialog(this, "Cập nhật khoa thành công!");
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật khoa thất bại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
            if (success) {
                if (this.getOwner() instanceof DepartmentManagementForm) {
                    ((DepartmentManagementForm) this.getOwner()).loadDepartmentToTable();
                }
                this.dispose();
            }
        }catch (NumberFormatException e) {
             JOptionPane.showMessageDialog(this, "Phí khám phải là một con số.", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Đã có lỗi xảy ra: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AddDepartmentDialog dialog = new AddDepartmentDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDepartmentName;
    private javax.swing.JLabel LabelDescription;
    private javax.swing.JLabel LabelconcultationFee;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField txtConsultationFee;
    private javax.swing.JTextField txtDepartmentName;
    private javax.swing.JTextField txtDescription;
    // End of variables declaration//GEN-END:variables
}
